### ISSUE TITLE
It broken

### ISSUE THREAD

**Issue by TheRubberDuckie** [Evilmedic/Snek#1]
Hi mister LIu
This prograam do not werk proper because it do not run proper. iT say i need java thing to work. i dont know why i need java drink in computer to work. please make fix fast so i can playy sneke.
Love,
Duckie

**Comment by Evilmedic** [comment]
no

**Comment by ShashyCuber** [comment]
I think you need Americano Java inorder to make it werk

**Comment by TheRubberDuckie** [comment]
Hi again mister LiU,
i beleif that computerr tell me i need java drink. I reallly do not want to buy machine to make for snek to work. can you please make compatibale with windows 98. thank you in advance
Love,
Duckie
